# Generated by Django 5.0.4 on 2024-04-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medico", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Especialidades",
            new_name="Especialidade",
        ),
    ]
